### ISSUE TITLE
sus

### ISSUE THREAD

**Issue by JohnShiozo** [josesilveiraa/1pop#1]
can i hack 1pop.club using the back end? 😳😳😳😳😳😳😳😳😳😳😳😳😳😳

**Comment by josesilveiraa** [comment]
yeah surely I found a serious vulnerability, but Hero doesn't wants to listen to me...
(I'm talking serious btw)

**Comment by JohnShiozo** [comment]
![sus](https://user-images.githubusercontent.com/66097391/119425453-cbec7e00-bcdd-11eb-9b63-da4e0e062c26.png)
